name: forms

services:
  admin:
    read_only: true
    tmpfs:
      - /tmp
    build:
      args:
        - BUNDLE_WITHOUT=
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-admin
      target: build
    command: >
      sh -c "
        bin/rails db:prepare &&
        exec rails s --restart
      "
    depends_on:
      - postgres
      - redis
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres
      - GOVUK_APP_DOMAIN=example.org
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_DEVELOPMENT_HOSTS=admin:3000
      - SECRET_KEY_BASE=dummyvalue
      - SETTINGS__FORMS_RUNNER__URL=http://localhost:3001
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ../../forms-admin:/app:cached
      - admin-bundle:/usr/local/bundle
      - admin-bundle-user-home:/home/ruby/.bundle
      - admin-node-modules:/app/node_modules
      - admin-tmp:/app/tmp
      - admin-npm:/home/ruby/.npm

  product-page:
    read_only: true
    tmpfs:
      - /tmp
    build:
      args:
        - BUNDLE_WITHOUT=
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-product-page
      target: build
    command: rails s --restart -p 3002
    environment:
      - BINDING=0.0.0.0
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - SECRET_KEY_BASE=dummyvalue
    ports:
      - "127.0.0.1:3002:3002"
    stdin_open: true
    tty: true
    volumes:
      - ../../forms-product-page:/app:cached
      - product-page-bundle:/usr/local/bundle
      - product-page-bundle-user-home:/home/ruby/.bundle
      - product-page-node-modules:/app/node_modules
      - product-page-tmp:/app/tmp
      - product-page-npm:/home/ruby/.npm

  runner:
    read_only: true
    tmpfs:
      - /tmp
    build:
      args:
        - BUNDLE_WITHOUT=
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-runner
      target: build
    command: >
      sh -c "
        bin/rails db:prepare &&
        exec rails s --restart -p 3001
      "
    depends_on:
      - postgres
      - redis
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres
      - QUEUE_DATABASE_URL=postgres://postgres:postgres@postgres
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis/
      - SECRET_KEY_BASE=dummyvalue
      - SETTINGS__FORMS_API__BASE_URL=http://admin:3000
    ports:
      - "127.0.0.1:3001:3001"
    stdin_open: true
    tty: true
    volumes:
      - ../../forms-runner:/app:cached
      - runner-bundle:/usr/local/bundle
      - runner-bundle-user-home:/home/ruby/.bundle
      - runner-node-modules:/app/node_modules
      - runner-tmp:/app/tmp
      - runner-npm:/home/ruby/.npm

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:16.6
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: valkey/valkey:8
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data

volumes:
  admin-bundle:
  admin-bundle-user-home:
  admin-node-modules:
  admin-tmp:
  admin-npm:
  product-page-bundle:
  product-page-bundle-user-home:
  product-page-node-modules:
  product-page-tmp:
  product-page-npm:
  runner-bundle:
  runner-bundle-user-home:
  runner-node-modules:
  runner-tmp:
  runner-npm:
  postgres:
  redis-data:
