version: "2.4"

services:
  forms-admin:
    build:
      context: ../../forms-admin
      args:
        - RAILS_ENV=development
        - NODE_ENV=development
    environment:
      - API_BASE=http://forms-api:9292
      - API_KEY=development_key
      - DATABASE_URL=postgres://forms_admin:forms_admin@postgres/forms_admin
      - GDS_SSO_OAUTH_ID=example.org
      - GDS_SSO_OAUTH_SECRET=secret
      - GDS_SSO_STRATEGY=mock
      - GOVUK_APP_DOMAIN=example.org
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
      - SECRET_KEY_BASE=assets
    volumes:
      - "../../forms-admin:/app:cached"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 3000:3000

  forms-api:
    build:
      context: ../../forms-api
    environment:
      - API_KEY=development_key
      - DATABASE_URL=postgres://forms_api:forms_api@postgres/forms_api
      - RACK_ENV=development
    volumes:
      - "../../forms-api:/app:cached"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 9292:9292

  forms-runner:
    build:
      context: "../../forms-runner"
      args:
        - RAILS_ENV=development
        - NODE_ENV=development
    environment:
      - API_BASE=http://forms-api:9292
      - API_KEY=development_key
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
      - SECRET_KEY_BASE=dummyvalue
    depends_on:
      redis:
        condition: service_started
    ports:
      - 3001:3000
    volumes:
      - "../../forms-runner:/app:cached"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  postgres:
