version: "2.4"

services:
  forms-admin:
    build:
      context: ../../forms-admin
      target: build
      args:
        - RAILS_ENV=development
        - NODE_ENV=development
    environment:
      - DATABASE_URL=postgres://forms_admin:forms_admin@postgres
      - GDS_SSO_OAUTH_ID=example.org
      - GDS_SSO_OAUTH_SECRET=secret
      - GDS_SSO_STRATEGY=mock
      - GOVUK_APP_DOMAIN=example.org
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
      - SECRET_KEY_BASE=assets
      - SETTINGS__FORMS_API__BASE_URL=${SETTINGS__FORMS_API__BASE_URL}
      - SETTINGS__FORMS_RUNNER__URL=http://localhost:3001
    volumes:
      - "../../forms-admin:/app:cached"
      - forms-admin-node-modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "
        bundle config unset --local without &&
        bin/setup &&
        rails s -b 0.0.0.0
      "

  forms-api:
    build:
      context: ../../forms-api
      target: build
    environment:
      - SETTINGS__FORMS_API__AUTHENTICATION_KEY=development_key
      - DATABASE_URL=postgres://forms_api:forms_api@postgres
      - RACK_ENV=development
      - SECRET_KEY_BASE=dummy_value
    volumes:
      - "../../forms-api:/app:cached"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 9292:9292
    command: >
      sh -c "
        bin/setup &&
        rails s -b 0.0.0.0 -p 9292
      "

  forms-runner:
    build:
      context: "../../forms-runner"
      target: build
      args:
        - RAILS_ENV=development
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
      - REDIS_URL=redis://redis/
      - SECRET_KEY_BASE=dummyvalue
      - SETTINGS__FORMS_API__BASE_URL=${SETTINGS__FORMS_API__BASE_URL}
    volumes:
      - "../../forms-runner:/app:cached"
      - forms-runner-node-modules:/app/node_modules
    depends_on:
      redis:
        condition: service_started
    ports:
      - 3001:3000
    command: >
      sh -c "
        bundle config unset --local without &&
        bin/setup &&
        rails s -b 0.0.0.0
      "

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  forms-admin-node-modules:
  forms-runner-node-modules:
  redis-data:
  postgres:
