services:
  forms-admin:
    read_only: true
    tmpfs:
      - /tmp
    build:
      args:
        - BUNDLE_WITHOUT=test
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-admin
      target: build
    command: >
      sh -c "
        bundle config unset --local without &&
        bundle install &&
        rails db:prepare &&
        npm install &&
        bin/vite build &&
        exec rails s --restart
      "
    depends_on:
      - postgres
      - redis
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres
      - GDS_SSO_OAUTH_ID=example.org
      - GDS_SSO_OAUTH_SECRET=secret
      - GDS_SSO_STRATEGY=mock
      - GOVUK_APP_DOMAIN=example.org
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_DEVELOPMENT_HOSTS=forms-admin:3000
      - SECRET_KEY_BASE=assets
      - SETTINGS__FORMS_RUNNER__URL=http://localhost:3001
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ../../forms-admin:/app:cached
      - forms-admin-bundle:/usr/local/bundle
      - forms-admin-node-modules:/app/node_modules
      - forms-admin-tmp:/app/tmp
      - forms-admin-npm:/home/ruby/.npm

  forms-product-page:
    read_only: true
    tmpfs:
      - /tmp
    build:
      args:
        - BUNDLE_WITHOUT=test
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-product-page
      target: build
    command: >
      sh -c "
        bundle install &&
        npm install &&
        bin/vite build &&
        exec rails s --restart -p 3002
      "
    environment:
      - BINDING=0.0.0.0
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - SECRET_KEY_BASE=dummyvalue
    ports:
      - "127.0.0.1:3002:3002"
    volumes:
      - ../../forms-product-page:/app:cached
      - forms-product-page-bundle:/usr/local/bundle
      - forms-product-page-node-modules:/app/node_modules
      - forms-product-page-tmp:/app/tmp
      - forms-product-page-npm:/home/ruby/.npm

  forms-runner:
    read_only: true
    tmpfs:
      - /tmp
    build:
      args:
        - BUNDLE_WITHOUT=test
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-runner
      target: build
    command: >
      sh -c "
        bundle install &&
        rails db:prepare &&
        npm install &&
        bin/vite build &&
        exec rails s --restart -p 3001
      "
    depends_on:
      - postgres
      - redis
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres
      - QUEUE_DATABASE_URL=postgres://postgres:postgres@postgres
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis/
      - SECRET_KEY_BASE=dummyvalue
      - SETTINGS__FORMS_API__BASE_URL=http://forms-admin:3000
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - ../../forms-runner:/app:cached
      - forms-runner-bundle:/usr/local/bundle
      - forms-runner-node-modules:/app/node_modules
      - forms-runner-tmp:/app/tmp
      - forms-runner-npm:/home/ruby/.npm

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:16.6
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: valkey/valkey:8
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data

volumes:
  forms-admin-bundle:
  forms-admin-node-modules:
  forms-admin-tmp:
  forms-admin-npm:
  forms-product-page-bundle:
  forms-product-page-node-modules:
  forms-product-page-tmp:
  forms-product-page-npm:
  forms-runner-bundle:
  forms-runner-node-modules:
  forms-runner-tmp:
  forms-runner-npm:
  postgres:
  redis-data:
