version: "2.4"

services:
  forms-admin:
    build:
      args:
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-admin
      target: build
    command: >
      sh -c "
        bundle config unset --local without &&
        bundle install &&
        rails db:prepare &&
        exec rails s
      "
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://forms_admin:forms_admin@postgres/forms_admin
      - GDS_SSO_OAUTH_ID=example.org
      - GDS_SSO_OAUTH_SECRET=secret
      - GDS_SSO_STRATEGY=mock
      - GOVUK_APP_DOMAIN=example.org
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
      - SECRET_KEY_BASE=assets
      - SETTINGS__FORMS_API__AUTH_KEY=development_key
      - SETTINGS__FORMS_API__BASE_URL=${SETTINGS__FORMS_API__BASE_URL}
      - SETTINGS__FORMS_RUNNER__URL=http://localhost:3001
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "3000:3000"
    volumes:
      - ../../forms-admin:/app:cached
      - forms-admin-bundle:/usr/local/bundle
      - forms-admin-tmp:/app/tmp

  forms-api:
    build:
      context: ../../forms-api
      target: build
    command: >
      sh -c "
        bundle install &&
        rails db:prepare &&
        exec rails s -p 9292
      "
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://forms_api:forms_api@postgres/forms_api
      - RACK_ENV=development
      - SECRET_KEY_BASE=dummy_value
      - SETTINGS__FORMS_API__AUTHENTICATION_KEY=development_key
    ports:
      - "9292:9292"
    volumes:
      - ../../forms-api:/app:cached
      - forms-api-bundle:/usr/local/bundle
      - forms-api-tmp:/app/tmp

  forms-runner:
    build:
      args:
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-runner
      target: build
    command: >
      sh -c "
        bundle install &&
        exec rails s -p 3001
      "
    depends_on:
      redis:
        condition: service_started
    environment:
      - BINDING=0.0.0.0
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
      - REDIS_URL=redis://redis/
      - SECRET_KEY_BASE=dummyvalue
      - SETTINGS__FORMS_API__AUTH_KEY=development_key
      - SETTINGS__FORMS_API__BASE_URL=${SETTINGS__FORMS_API__BASE_URL}
    ports:
      - "3001:3001"
    volumes:
      - ../../forms-runner:/app:cached
      - forms-runner-bundle:/usr/local/bundle
      - forms-runner-tmp:/app/tmp

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d/

  redis:
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  forms-admin-bundle:
  forms-admin-tmp:
  forms-api-bundle:
  forms-api-tmp:
  forms-runner-bundle:
  forms-runner-tmp:
  postgres:
  redis-data:
