version: "2.4"

services:
  forms-admin:
    build:
      args:
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-admin
      target: build
    command: >
      sh -c "
        bundle config unset --local without &&
        bundle install &&
        rails db:prepare &&
        npm install &&
        bin/vite build &&
        exec rails s --restart
      "
    depends_on:
      - postgres
      - redis
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres
      - GDS_SSO_OAUTH_ID=example.org
      - GDS_SSO_OAUTH_SECRET=secret
      - GDS_SSO_STRATEGY=mock
      - GOVUK_APP_DOMAIN=example.org
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - SECRET_KEY_BASE=assets
      - SETTINGS__FORMS_API__BASE_URL=${SETTINGS__FORMS_API__BASE_URL}
      - SETTINGS__FORMS_RUNNER__URL=http://localhost:3001
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ../../forms-admin:/app:cached
      - forms-admin-bundle:/usr/local/bundle
      - forms-admin-node-modules:/app/node_modules
      - forms-admin-tmp:/app/tmp

  forms-api:
    build:
      context: ../../forms-api
      target: build
    command: >
      sh -c "
        bundle install &&
        rails db:prepare &&
        exec rails s --restart -p 9292
      "
    depends_on:
      - postgres
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres
      - RACK_ENV=development
      - RAILS_ENV=development
      - SECRET_KEY_BASE=dummy_value
    ports:
      - "127.0.0.1:9292:9292"
    volumes:
      - ../../forms-api:/app:cached
      - forms-api-bundle:/usr/local/bundle
      - forms-api-tmp:/app/tmp

  forms-product-page:
    build:
      args:
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-product-page
      target: build
    command: >
      sh -c "
        bundle install &&
        npm install &&
        bin/vite build &&
        exec rails s --restart -p 3002
      "
    environment:
      - BINDING=0.0.0.0
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - SECRET_KEY_BASE=dummyvalue
    ports:
      - "127.0.0.1:3002:3002"
    volumes:
      - ../../forms-product-page:/app:cached
      - forms-product-page-bundle:/usr/local/bundle
      - forms-product-page-node-modules:/app/node_modules
      - forms-product-page-tmp:/app/tmp

  forms-runner:
    build:
      args:
        - NODE_ENV=development
        - RAILS_ENV=development
      context: ../../forms-runner
      target: build
    command: >
      sh -c "
        bundle install &&
        rails db:prepare &&
        npm install &&
        bin/vite build &&
        exec rails s --restart -p 3001
      "
    depends_on:
      - postgres
      - redis
    environment:
      - BINDING=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres
      - NODE_ENV=development
      - RACK_ENV=development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis/
      - SECRET_KEY_BASE=dummyvalue
      - SETTINGS__FORMS_API__BASE_URL=${SETTINGS__FORMS_API__BASE_URL}
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - ../../forms-runner:/app:cached
      - forms-runner-bundle:/usr/local/bundle
      - forms-runner-node-modules:/app/node_modules
      - forms-runner-tmp:/app/tmp

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:13
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data

volumes:
  forms-admin-bundle:
  forms-admin-node-modules:
  forms-admin-tmp:
  forms-api-bundle:
  forms-api-tmp:
  forms-product-page-bundle:
  forms-product-page-node-modules:
  forms-product-page-tmp:
  forms-runner-bundle:
  forms-runner-node-modules:
  forms-runner-tmp:
  postgres:
  redis-data:
