[env]
_.path = "support/forms-cli/bin"

[tools]
"go:github.com/hashicorp/terraform-config-inspect" = "latest"
hcl2json = "0.6.8"
infracost = "0.10.42"
tflint = "0.59.1"
checkov = "3.2.386"

[settings]
idiomatic_version_file_enable_tools = ["terraform", "ruby"]
