version: 0.2
artifacts:
  enable-symlinks: yes
phases:
  install:
    commands:
      # install terraform
      - "# shellcheck disable=SC2155"
      - set -e
      - uname -a
      - yum install -y yum-utils
      - curl "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o "terraform-${TERRAFORM_VERSION}.zip"
      - unzip "terraform-${TERRAFORM_VERSION}.zip"
      - mv terraform /usr/local/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - echo "Assuming role ${DEPLOYER_ROLE_ARN}"
      - aws sts get-caller-identity
      - sts="$(aws sts assume-role --role-arn "${DEPLOYER_ROLE_ARN}" --role-session-name "deployer" --external-id "${ENVIRONMENT}")"
      - export AWS_ACCESS_KEY_ID="$(echo "${sts}" | jq '.Credentials.AccessKeyId' -r )"
      - export AWS_SECRET_ACCESS_KEY="$(echo "${sts}" | jq '.Credentials.SecretAccessKey' -r )"
      - export AWS_SESSION_TOKEN="$(echo "${sts}" | jq '.Credentials.SessionToken' -r )"
      - aws sts get-caller-identity
      - cd "infra/deployments/forms/${ROOT_NAME}"
      - terraform init --backend-config "../../account/tfvars/backends/${ENVIRONMENT}.tfvars"
      - terraform plan -var-file "../tfvars/${ENVIRONMENT}.tfvars"
