---
roles:
  - role: arn:aws:iam::711966560482:role/codepipeline-readonly
    gds_cli_role: forms-deploy-readonly
  - role: arn:aws:iam::498160065950:role/codepipeline-readonly
    gds_cli_role: forms-dev-readonly
  - role: arn:aws:iam::443944947292:role/codepipeline-readonly
    gds_cli_role: forms-prod-readonly
  - role: arn:aws:iam::972536609845:role/codepipeline-readonly
    gds_cli_role: forms-staging-readonly
  - role: arn:aws:iam::619109835131:role/codepipeline-readonly
    gds_cli_role: forms-user-research-readonly

groups:
  "Apply Terraform":
    - "apply-forms-terraform-staging"
    - "apply-forms-terraform-production"
    - "apply-forms-terraform-user-research"
    - "apply-forms-terraform-dev"

  "Product pages":
    - "forms-product-page-image-builder"
    - "deploy-forms-product-page-container-staging"
    - "deploy-forms-product-page-container-production"
    - "deploy-forms-product-page-container-user-research"
    - "deploy-forms-product-page-container-dev"

  "API":
    - "forms-api-main-branch"
    - "forms-api-image-builder"
    - "deploy-forms-api-container-staging"
    - "deploy-forms-api-container-production"
    - "deploy-forms-api-container-user-research"
    - "deploy-forms-api-container-dev"

  "Admin":
    - "forms-admin-main-branch"

  "Runner":
    - "forms-runner-main-branch"
    - "forms-runner-image-builder"
    - "deploy-forms-runner-container-staging"
    - "deploy-forms-runner-container-production"
    - "deploy-forms-runner-container-user-research"
    - "deploy-forms-runner-container-dev"

  "Pipeline visualiser":
    - "deploy-pipeline-visualiser"

  "End to end tests":
    - "e2e-image"
