name: Deploy forms-admin to Staging

on:
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: "Ref to deploy (branch name, tag name, or SHA)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    env:
      CF_API: "https://api.london.cloud.service.gov.uk"
      CF_ORG: "gds-govuk-forms"
      CF_SPACE: "forms-admin-staging"
      SIGNON_USERNAME: ${{ secrets.SIGNON_USERNAME }}
      SIGNON_PASSWORD: ${{ secrets.SIGNON_PASSWORD }}
      SIGNON_OTP: ${{ secrets.SIGNON_OTP }}

    steps:
      - name: Checkout forms-admin
        uses: actions/checkout@v2
        with:
          repository: alphagov/forms-admin
          ref: ${{ inputs.ref_to_deploy }}
          path: main
      - uses: nanasess/setup-chromedriver@v1.0.1
      - name: Checkout capybara tests
        uses: actions/checkout@v2
        with:
          path: tests
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: tests/capybara
      - name: Run tests
        run: bundle exec rspec tests/capybara/spec/features/complete_spec.rb
