name: Deploy forms-admin to GOV.UK PaaS Staging environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    env:
      CF_API: "https://api.london.cloud.service.gov.uk"
      CF_ORG: "gds-govuk-forms"
      CF_SPACE: "forms-admin-staging"

    steps:
      - name: Checkout forms-admin
        uses: actions/checkout@v2
        with:
          repository: alphagov/forms-admin

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124 # ruby 3.1.1
        with:
          bundler-cache: true

      - name: Precompile assets
        run: bundle exec rake assets:precompile

      - name: Install cloudfoundry
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Authenticate
        env:
          CF_USERNAME: ${{ secrets.STAGING_CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.STAGING_CF_PASSWORD }}
        run: |
          echo "Logging into $CF_ORG/$CF_SPACE..."
          cf api "${CF_API}"
          cf auth
          cf target -o "${CF_ORG}" -s "${CF_SPACE}"
          
      - name: Deploy to GOV.UK PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf push --strategy rolling \
            --var PAAS_ENVIRONMENT=staging \
            --var SENTRY_DSN=${{ secrets.ADMIN_SENTRY_DSN }} \
            --var GDS_SSO_OAUTH_ID=unset \
            --var GDS_SSO_OAUTH_SECRET=unset \
            --var GOVUK_APP_DOMAIN=unset \
            --var API_BASE=https://forms-api-staging.london.cloudapps.digital \
            --var RUNNER_BASE=https://forms-runner-staging.london.cloudapps.digital
          cf logout
