name: Deploy admin to staging

on:
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: "Ref to deploy (branch name, tag name, or SHA)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    env:
      CF_API: "https://api.london.cloud.service.gov.uk"
      CF_ORG: "gds-govuk-forms"
      CF_SPACE: "forms-admin-staging"
      SIGNON_USERNAME: ${{ secrets.SIGNON_USERNAME }}
      SIGNON_PASSWORD: ${{ secrets.SIGNON_PASSWORD }}
      SIGNON_OTP: ${{ secrets.SIGNON_OTP }}
      FORMS_ADMIN_URL: https://admin.staging.forms.service.gov.uk/
      SETTINGS__GOVUK_NOTIFY__API_KEY: ${{ secrets.SETTINGS__GOVUK_NOTIFY__API_KEY }}

    steps:
      - name: Checkout forms-admin
        uses: actions/checkout@v3
        with:
          repository: alphagov/forms-admin
          ref: ${{ inputs.ref_to_deploy }}
          path: main

      - name: Install cloudfoundry
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Authenticate
        env:
          CF_USERNAME: ${{ secrets.STAGING_CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.STAGING_CF_PASSWORD }}
        run: |
          echo "Logging into $CF_ORG/$CF_SPACE..."
          cf api "${CF_API}"
          cf auth
          cf target -o "${CF_ORG}" -s "${CF_SPACE}"

      - name: Precompile assets
        run: cd main && npm ci && npx vite build

      - name: Deploy to GOV.UK PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cd main && cf push --strategy rolling \
            --var PAAS_ENVIRONMENT=staging \
            --var SETTINGS__MAINTENANCE_MODE__ENABLED=false \
            --var INSTANCES=2 \
            --var SETTINGS__SENTRY__DSN=${{ secrets.ADMIN_SENTRY_DSN }} \
            --var SETTINGS__SENTRY__ENVIRONMENT=staging \
            --var SETTINGS__GOVUK_NOTIFY__API_KEY=${{ secrets.SETTINGS__GOVUK_NOTIFY__API_KEY }} \
            --var GDS_SSO_OAUTH_ID=${{ secrets.GDS_SSO_OAUTH_ID }} \
            --var GDS_SSO_OAUTH_SECRET=${{ secrets.GDS_SSO_OAUTH_SECRET }} \
            --var GOVUK_APP_DOMAIN=staging.publishing.service.gov.uk \
            --var SETTINGS__FORMS_API__AUTH_KEY=${{ secrets.FORMS_API_KEY_FOR_FORMS_ADMIN }} \
            --var SETTINGS__FORMS_API__BASE_URL=https://forms-api-staging.london.cloudapps.digital \
            --var SETTINGS__FORMS_RUNNER__URL=https://submit.staging.forms.service.gov.uk \
            --var SETTINGS__FEATURES__BASIC_ROUTING=true
          cf logout

      - uses: nanasess/setup-chromedriver@v2

      - name: Checkout capybara tests
        uses: actions/checkout@v3
        with:
          path: tests

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: tests/capybara

      - name: Run tests
        run: cd tests/capybara && bundle exec rspec spec/features/complete_spec.rb
