name: Deploy forms-admin to Production

on:
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: "Ref to deploy (branch name, tag name, or SHA)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      CF_API: "https://api.london.cloud.service.gov.uk"
      CF_ORG: "gds-govuk-forms"
      CF_SPACE: "forms-admin-production"
      SIGNON_USERNAME: ${{ secrets.SIGNON_USERNAME }}
      SIGNON_PASSWORD: ${{ secrets.SIGNON_PASSWORD }}
      SIGNON_OTP: ${{ secrets.SIGNON_OTP }}
      FORMS_ADMIN_URL: https://admin.forms.service.gov.uk/
      SETTINGS__GOVUK_NOTIFY__API_KEY: ${{ secrets.SETTINGS__GOVUK_NOTIFY__API_KEY }}

    steps:
      - name: Checkout forms-admin
        uses: actions/checkout@v2
        with:
          repository: alphagov/forms-admin
          ref: ${{ inputs.ref_to_deploy }}

      - name: Install cloudfoundry
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Authenticate
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: |
          echo "Logging into $CF_ORG/$CF_SPACE..."
          cf api "${CF_API}"
          cf auth
          cf target -o "${CF_ORG}" -s "${CF_SPACE}"

      - name: Deploy to GOV.UK PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf push --strategy rolling \
            --var PAAS_ENVIRONMENT=production \
            --var INSTANCES=2 \
            --var SENTRY_DSN=${{ secrets.ADMIN_SENTRY_DSN }} \
            --var SETTINGS__GOVUK_NOTIFY__API_KEY=${{ secrets.SETTINGS__GOVUK_NOTIFY__API_KEY }} \
            --var GDS_SSO_OAUTH_ID=${{ secrets.GDS_SSO_OAUTH_ID }} \
            --var GDS_SSO_OAUTH_SECRET=${{ secrets.GDS_SSO_OAUTH_SECRET }} \
            --var GOVUK_APP_DOMAIN=publishing.service.gov.uk \
            --var API_BASE=https://forms-api-production.london.cloudapps.digital \
            --var API_KEY=${{ secrets.FORMS_API_KEY }} \
            --var RUNNER_BASE=https://submit.forms.service.gov.uk
          cf logout

      - uses: nanasess/setup-chromedriver@v1.0.1

      - name: Checkout capybara tests
        uses: actions/checkout@v2
        with:
          path: tests

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: tests/capybara

      - name: Run tests
        run: cd tests/capybara && bundle exec rspec spec/features/complete_spec.rb
