name: Deploy forms-runner to Staging environment

on:
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: "Ref to deploy (branch name, tag name, or SHA)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    env:
      CF_API: "https://api.london.cloud.service.gov.uk"
      CF_ORG: "gds-govuk-forms"
      CF_SPACE: "forms-runner-staging"

    steps:
      - name: Checkout forms-runner
        uses: actions/checkout@v2
        with:
          repository: alphagov/forms-runner
          ref: ${{ inputs.ref_to_deploy }}

      - name: Install cloudfoundry
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli

      - name: Authenticate
        env:
          CF_USERNAME: ${{ secrets.STAGING_CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.STAGING_CF_PASSWORD }}
        run: |
          echo "Logging into $CF_ORG/$CF_SPACE..."
          cf api "${CF_API}"
          cf auth
          cf target -o "${CF_ORG}" -s "${CF_SPACE}"

      - name: Deploy to GOV.UK PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf push --strategy rolling \
            --var PAAS_ENVIRONMENT=staging \
            --var SENTRY_DSN=${{ secrets.RUNNER_SENTRY_DSN }} \
            --var API_BASE=https://forms-api-staging.london.cloudapps.digital \
            --var API_KEY=${{ secrets.STAGING_FORMS_API_KEY }} \
            --var NOTIFY_API_KEY=${{ secrets.RUNNER_NOTIFY_API_KEY }}
          cf logout
