name: "Test Forms Cli"
on:
  push:
    branches: [forms_cli]
    paths:
      - 'support/forms-cli/**'
  pull_request:
    branches: [main]
    paths:
      - 'support/forms-cli/**'
  merge_group:
    types: [checks_requested]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: support/forms-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@bd03e04863f52d169e18a2b190e8fa6b84938215 # v1.170.0
        with:
          bundler-cache: true
          working-directory: support/forms-cli
      - name: Run linter
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
