name: "Test Forms Cli"
on:
  push:
    branches: [forms_cli]
    paths:
      - "support/forms-cli/**"
  pull_request:
    branches: [main]
    paths:
      - "support/forms-cli/**"
  merge_group:
    types: [checks_requested]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: support/forms-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Determine Ruby version
        id: determine-ruby-version
        run: |
          echo "RUBY_VERSION=$(cat ../../.ruby-version)" >> "$GITHUB_OUTPUT"
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@868b3f088412f139260f27f5b148179b9dd6b008 # v1.208.0
        with:
          bundler-cache: true
          ruby-version: ${{steps.determine-ruby-version.outputs.RUBY_VERSION}}
          working-directory: support/forms-cli
      - name: Run tests
        run: bundle exec rspec
