name: "Pipeline Visualiser checks"
on:
  pull_request:
    branches: [main]
    paths:
      - "support/pipeline-visualiser/**"
      - ".github/workflows/pipeline-visualiser.yml"
  merge_group:
    types: [checks_requested]
jobs:
  build_container:
    runs-on: ubuntu-24.04-arm # The container will ultimately be built for arm64 and run on arm64, so we should test it on arm64.
    name: "Build container"
    defaults:
      run:
        working-directory: support/pipeline-visualiser
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run docker build
        run: docker build .

  run_tests:
    runs-on: ubuntu-24.04-arm
    name: "Build and test"
    defaults:
      run:
        working-directory: support/pipeline-visualiser
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Determine Ruby version
        id: determine-ruby-version
        run: |
          echo "RUBY_VERSION=$(cat ../../.ruby-version)" >> "$GITHUB_OUTPUT"
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          bundler-cache: true
          ruby-version: ${{steps.determine-ruby-version.outputs.RUBY_VERSION}}
          working-directory: support/pipeline-visualiser
      - name: Run pipeline visualiser tests
        run: bundle exec rspec
