name: "Lint Workflows"

on:
  workflow_call:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download actionlint
        id: get_actionlint
        run: |
          curl -L "https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz" | tar -xvz actionlint
          chmod +x actionlint
          sudo mv actionlint /usr/local/bin/actionlint
        shell: bash
      - name: Check workflow files
        run: actionlint -color
        shell: bash
